import { Injectable } from "@angular/core";
import { cainUserId, ilkaUserId } from "../../shared/data/users";
import { VocabList } from "../models";
import { AuxiliaryVerb, Case, FixedPlurality, Gender, ReflexiveCase, Separability, Transitivity, WordType } from "../models/data";

@Injectable()
export class InMemoryDataProvider {
  public seed(): VocabList[] {
    return [{
      id: '83d1b66e-d2e9-9db8-d1f1-3f9027dd5aed',
      userId: cainUserId,
      name: 'Kitchen',
      description: 'A collection of common kitchen items.',
      listItems: [
        {
          id: '473573a8-86d7-4b64-8e51-96fead598a7c',
          wordType: WordType.Verb,
          isWeakMasculineNoun: null,
          reflexiveCase: null,
          separability: Separability.None,
          transitivity: Transitivity.Both,
          thirdPersonPresent: "isst",
          thirdPersonImperfect: "aß",
          auxiliaryVerb: AuxiliaryVerb.Haben,
          perfect: "gegessen",
          gender: null,
          german: 'essen',
          plural: null,
          preposition: null,
          prepositionCase: null,
          comparative: null,
          superlative: null,
          english: 'to reply, retort',
          vocabListId: '83d1b66e-d2e9-9db8-d1f1-3f9027dd5aed',
          fixedPlurality: null,
        },
        {
          id: 'aeedd2e9-daa3-4b12-aaf0-b96dad211441',
          wordType: WordType.Verb,
          isWeakMasculineNoun: null,
          reflexiveCase: ReflexiveCase.Accusative,
          separability: Separability.None,
          transitivity: Transitivity.Transitive,
          thirdPersonPresent: null,
          thirdPersonImperfect: null,
          auxiliaryVerb: AuxiliaryVerb.Haben,
          perfect: null,
          gender: null,
          german: 'begnügen',
          plural: null,
          preposition: "mit",
          prepositionCase: Case.Dative,
          comparative: null,
          superlative: null,
          english: 'To content oneself with',
          vocabListId: '83d1b66e-d2e9-9db8-d1f1-3f9027dd5aed',
          fixedPlurality: null,
        },
        {
          id: 'c2f10b98-0c0c-4a12-a525-19e3dc64e899',
          wordType: WordType.Verb,
          isWeakMasculineNoun: null,
          reflexiveCase: null,
          separability: Separability.Separable,
          transitivity: Transitivity.Intransitive,
          thirdPersonPresent: "ankommt",
          thirdPersonImperfect: "ankam",
          auxiliaryVerb: AuxiliaryVerb.Sein,
          perfect: "angekommen",
          gender: null,
          german: 'ankommen',
          plural: null,
          preposition: null,
          prepositionCase: null,
          comparative: null,
          superlative: null,
          english: 'to arrive',
          vocabListId: '83d1b66e-d2e9-9db8-d1f1-3f9027dd5aed',
          fixedPlurality: null,
        },
        {
          id: 'dba640e1-682f-4f24-a303-1ae74fa762e0',
          wordType: WordType.Verb,
          isWeakMasculineNoun: null,
          reflexiveCase: null,
          separability: Separability.None,
          transitivity: Transitivity.Intransitive,
          thirdPersonPresent: "ist",
          thirdPersonImperfect: "war",
          auxiliaryVerb: AuxiliaryVerb.Sein,
          perfect: "gewesen",
          gender: null,
          german: 'sein',
          plural: null,
          preposition: null,
          prepositionCase: null,
          comparative: null,
          superlative: null,
          english: 'to be',
          vocabListId: '83d1b66e-d2e9-9db8-d1f1-3f9027dd5aed',
          fixedPlurality: null,
        },
        {
          id: 'e64d6146-93be-467b-a19e-8749a363b08b',
          wordType: WordType.Noun,
          isWeakMasculineNoun: false,
          reflexiveCase: null,
          separability: null,
          transitivity: null,
          thirdPersonPresent: null,
          thirdPersonImperfect: null,
          auxiliaryVerb: null,
          perfect: null,
          gender: Gender.Feminine,
          german: 'Eifersucht',
          plural: null,
          preposition: "auf",
          prepositionCase: Case.Accusative,
          comparative: null,
          superlative: null,
          english: 'jealousy',
          vocabListId: '83d1b66e-d2e9-9db8-d1f1-3f9027dd5aed',
          fixedPlurality: FixedPlurality.None,
        },
        {
          id: '1321a874-30d1-4be4-83bb-2c4e0f6c79da',
          wordType: WordType.Noun,
          isWeakMasculineNoun: false,
          reflexiveCase: null,
          separability: null,
          transitivity: null,
          thirdPersonPresent: null,
          thirdPersonImperfect: null,
          auxiliaryVerb: null,
          perfect: null,
          gender: Gender.Masculine,
          german: 'Verrat',
          plural: null,
          preposition: "an",
          prepositionCase: Case.Dative,
          comparative: null,
          superlative: null,
          english: 'betrayal',
          vocabListId: '83d1b66e-d2e9-9db8-d1f1-3f9027dd5aed',
          fixedPlurality: FixedPlurality.Singular,
        },
        {
          id: 'c020a16d-d135-4463-8b22-a7999cdd74a4',
          wordType: WordType.Noun,
          isWeakMasculineNoun: false,
          reflexiveCase: null,
          separability: null,
          transitivity: null,
          thirdPersonPresent: null,
          thirdPersonImperfect: null,
          auxiliaryVerb: null,
          perfect: null,
          gender: Gender.Masculine,
          german: 'Wasserkocher',
          plural: 'Wasserköcher',
          preposition: null,
          prepositionCase: null,
          comparative: null,
          superlative: null,
          english: 'kettle',
          vocabListId: '83d1b66e-d2e9-9db8-d1f1-3f9027dd5aed',
          fixedPlurality: FixedPlurality.None,
        },
        {
          id: '72cbb03f-b37a-4a41-ad93-0abd4dde28b7',
          wordType: WordType.Noun,
          isWeakMasculineNoun: true,
          reflexiveCase: null,
          separability: null,
          transitivity: null,
          thirdPersonPresent: null,
          thirdPersonImperfect: null,
          auxiliaryVerb: null,
          perfect: null,
          gender: Gender.Masculine,
          german: 'Löwe',
          plural: 'Löwen',
          preposition: null,
          prepositionCase: null,
          comparative: null,
          superlative: null,
          english: 'lion',
          vocabListId: '83d1b66e-d2e9-9db8-d1f1-3f9027dd5aed',
          fixedPlurality: FixedPlurality.None,
        },
        {
          id: 'e325e079-79c2-4478-9cc8-29ef80094e90',
          wordType: WordType.Verb,
          isWeakMasculineNoun: null,
          reflexiveCase: null,
          separability: Separability.None,
          transitivity: Transitivity.Both,
          thirdPersonPresent: null,
          thirdPersonImperfect: null,
          auxiliaryVerb: AuxiliaryVerb.Haben,
          perfect: null,
          gender: null,
          german: 'kochen',
          plural: null,
          preposition: null,
          prepositionCase: null,
          comparative: null,
          superlative: null,
          english: 'to cook',
          vocabListId: '83d1b66e-d2e9-9db8-d1f1-3f9027dd5aed',
          fixedPlurality: null,
        },
        {
          id: 'e545f0d0-aa5c-4a35-8bbd-0a5222ef48f5',
          wordType: WordType.Verb,
          isWeakMasculineNoun: null,
          reflexiveCase: null,
          separability: Separability.None,
          transitivity: Transitivity.Both,
          thirdPersonPresent: null,
          thirdPersonImperfect: null,
          auxiliaryVerb: AuxiliaryVerb.Haben,
          perfect: null,
          gender: null,
          german: 'entgegnen',
          plural: null,
          preposition: 'auf',
          prepositionCase: Case.Accusative,
          comparative: null,
          superlative: null,
          english: 'to reply, retort',
          vocabListId: '83d1b66e-d2e9-9db8-d1f1-3f9027dd5aed',
          fixedPlurality: null,
        },
        {
          id: '0a94e979-d8ba-45b6-a277-25e9f60de608',
          wordType: WordType.Adjective,
          isWeakMasculineNoun: null,
          reflexiveCase: null,
          separability: null,
          transitivity: null,
          thirdPersonPresent: null,
          thirdPersonImperfect: null,
          auxiliaryVerb: null,
          perfect: null,
          gender: null,
          german: 'gut',
          plural: null,
          preposition: null,
          prepositionCase: null,
          comparative: 'besser',
          superlative: 'beste',
          english: 'good',
          vocabListId: '83d1b66e-d2e9-9db8-d1f1-3f9027dd5aed',
          fixedPlurality: null,
        },
        {
          id: '97b053a7-35c2-4504-a649-846c1094ff12',
          wordType: WordType.Adverb,
          isWeakMasculineNoun: null,
          reflexiveCase: null,
          separability: null,
          transitivity: null,
          thirdPersonPresent: null,
          thirdPersonImperfect: null,
          auxiliaryVerb: null,
          perfect: null,
          gender: null,
          german: 'schnell',
          plural: null,
          preposition: null,
          prepositionCase: null,
          comparative: 'schneller',
          superlative: 'schnellste',
          english: 'quickly',
          vocabListId: '83d1b66e-d2e9-9db8-d1f1-3f9027dd5aed',
          fixedPlurality: null,
        }
      ],
      authorName: "Cain Harniess",
    },
    {
      id: '70d61107-380c-45b3-a5e4-6e021e4c2986',
      userId: cainUserId,
      name: 'Bedroom',
      description: 'Things in the room where you sleep.',
      listItems: [
        {
          id: '473573a8-86d7-4b64-8e51-96fead598a7c',
          wordType: WordType.Noun,
          isWeakMasculineNoun: false,
          reflexiveCase: null,
          separability: null,
          transitivity: null,
          thirdPersonPresent: null,
          thirdPersonImperfect: null,
          auxiliaryVerb: null,
          perfect: null,
          gender: Gender.Neuter,
          german: 'Bett',
          plural: "Betten",
          preposition: null,
          prepositionCase: null,
          comparative: null,
          superlative: null,
          english: 'bed',
          vocabListId: '70d61107-380c-45b3-a5e4-6e021e4c2986',
          fixedPlurality: FixedPlurality.None,
        },
      ],
      authorName: "Cain Harniess",
      },
      {
        id: '658fbe68-faf1-4490-9d12-6bce164e436a',
        userId: ilkaUserId,
        name: 'Bathroom',
        description: 'The cleanest room in the house.',
        listItems: [
          {
            id: 'e8885251-099c-4570-85f2-7da2ab093cad',
            wordType: WordType.Noun,
            isWeakMasculineNoun: false,
            reflexiveCase: null,
            separability: null,
            transitivity: null,
            thirdPersonPresent: null,
            thirdPersonImperfect: null,
            auxiliaryVerb: null,
            perfect: null,
            gender: Gender.Neuter,
            german: 'Bad',
            plural: "Bäder",
            preposition: null,
            prepositionCase: null,
            comparative: null,
            superlative: null,
            english: 'bath',
            vocabListId: '658fbe68-faf1-4490-9d12-6bce164e436a',
            fixedPlurality: FixedPlurality.None,
          },
        ],
        authorName: "Cain Harniess",
      }];
  }
}
