export { WordTypeValidationController } from "./word-type-validation.manager";
export { WordTypeValueController } from "./word-type-value.controller";
export { WordTypeFormManager } from "./word-type-form.manager";
export { WordTypeFormComponent } from "./word-type-form.component";
export { IrregularValueController } from "./irregular-value.controller";
export { IrregularValidationController } from "./irregular-validation.controller";
export { IrregularFormComponent } from "./irregular-form.component";
export { ModifierValidationController } from "./modifier-validation.controller";
export { ModifierValueController } from "./modifier-value.controller";
